-- ============================================================
-- Water IoT Dashboard - PostgreSQL schema
-- ============================================================

-- Remove old tables only if you are restarting the migration.
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS control_actions CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS sensor_logs CASCADE;
DROP TABLE IF EXISTS wards CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ------------------------------------------------------------
-- Users
-- ------------------------------------------------------------
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    role VARCHAR(20) NOT NULL DEFAULT 'user'
        CHECK (role IN ('user', 'operator')),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

-- ------------------------------------------------------------
-- Devices
-- ------------------------------------------------------------
CREATE TABLE devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_key VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL DEFAULT 'ESP32 Main Controller',
    ip_address VARCHAR(45) NOT NULL,
    tank_capacity_ml INTEGER NOT NULL DEFAULT 5000,
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Wards
-- ------------------------------------------------------------
CREATE TABLE wards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id INTEGER NOT NULL
        REFERENCES devices(id) ON DELETE CASCADE,

    ward_number SMALLINT NOT NULL
        CHECK (ward_number BETWEEN 1 AND 3),

    ward_name VARCHAR(100) NOT NULL,
    valve_gpio VARCHAR(10),

    UNIQUE (device_id, ward_number)
);

-- ------------------------------------------------------------
-- Sensor history
-- ------------------------------------------------------------
CREATE TABLE sensor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id INTEGER NOT NULL
        REFERENCES devices(id) ON DELETE CASCADE,

    tank_level_ml INTEGER NOT NULL,
    flow_rate_lpm NUMERIC(6,2) NOT NULL DEFAULT 0,

    ward1_ml INTEGER NOT NULL DEFAULT 0,
    ward2_ml INTEGER NOT NULL DEFAULT 0,
    ward3_ml INTEGER NOT NULL DEFAULT 0,

    active_ward SMALLINT NOT NULL DEFAULT 0
        CHECK (active_ward BETWEEN 0 AND 3),

    street_light BOOLEAN NOT NULL DEFAULT FALSE,

    light_mode VARCHAR(20) NOT NULL DEFAULT 'auto'
        CHECK (
            light_mode IN (
                'auto',
                'manual_on',
                'manual_off'
            )
        ),

    leak_detected BOOLEAN NOT NULL DEFAULT FALSE,
    dry_tank BOOLEAN NOT NULL DEFAULT FALSE,

    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sensor_logs_device_time
ON sensor_logs(device_id, recorded_at);

-- ------------------------------------------------------------
-- Water distribution schedules
-- ------------------------------------------------------------
CREATE TABLE schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id INTEGER NOT NULL
        REFERENCES devices(id) ON DELETE CASCADE,

    ward_number SMALLINT NOT NULL
        CHECK (ward_number BETWEEN 1 AND 3),

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    days_mask VARCHAR(27) NOT NULL
        DEFAULT 'MON,TUE,WED,THU,FRI,SAT,SUN',

    quota_ml INTEGER NOT NULL DEFAULT 1500,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_by INTEGER NOT NULL
        REFERENCES users(id),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Operator control history
-- ------------------------------------------------------------
CREATE TABLE control_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id INTEGER NOT NULL
        REFERENCES devices(id) ON DELETE CASCADE,

    user_id INTEGER NOT NULL
        REFERENCES users(id),

    action_type VARCHAR(30) NOT NULL
        CHECK (
            action_type IN (
                'valve_open',
                'valve_close',
                'light_on',
                'light_off',
                'light_auto',
                'refill'
            )
        ),

    target_ward SMALLINT
        CHECK (
            target_ward IS NULL
            OR target_ward BETWEEN 1 AND 3
        ),

    result VARCHAR(20) NOT NULL DEFAULT 'success'
        CHECK (result IN ('success', 'failed')),

    notes VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Alerts
-- ------------------------------------------------------------
CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    device_id INTEGER NOT NULL
        REFERENCES devices(id) ON DELETE CASCADE,

    alert_type VARCHAR(30) NOT NULL
        CHECK (
            alert_type IN (
                'leak',
                'dry_tank',
                'device_offline',
                'low_level'
            )
        ),

    severity VARCHAR(20) NOT NULL DEFAULT 'warning'
        CHECK (
            severity IN (
                'info',
                'warning',
                'critical'
            )
        ),

    message VARCHAR(255) NOT NULL,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

CREATE INDEX idx_alerts_device_resolved
ON alerts(device_id, is_resolved);

-- ------------------------------------------------------------
-- Initial device and ward records
-- ------------------------------------------------------------
INSERT INTO devices (
    id,
    device_key,
    name,
    ip_address,
    tank_capacity_ml
)
VALUES (
    1,
    'esp32-main',
    'ESP32 Main Controller',
    '192.168.1.50',
    5000
)
ON CONFLICT (device_key)
DO UPDATE SET
    ip_address = EXCLUDED.ip_address,
    tank_capacity_ml = EXCLUDED.tank_capacity_ml;

INSERT INTO wards (
    device_id,
    ward_number,
    ward_name,
    valve_gpio
)
VALUES
    (1, 1, 'Ward 1 - North Colony', 'GPIO25'),
    (1, 2, 'Ward 2 - East Colony', 'GPIO26'),
    (1, 3, 'Ward 3 - South Colony', 'GPIO27')
ON CONFLICT (device_id, ward_number)
DO UPDATE SET
    ward_name = EXCLUDED.ward_name,
    valve_gpio = EXCLUDED.valve_gpio;

-- Keep future generated device IDs above the manually inserted ID.
SELECT setval(
    pg_get_serial_sequence('devices', 'id'),
    (SELECT MAX(id) FROM devices)
);



SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;


SELECT pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conname = 'alerts_alert_type_check';


ALTER TABLE alerts
DROP CONSTRAINT IF EXISTS alerts_alert_type_check;

ALTER TABLE alerts
ADD CONSTRAINT alerts_alert_type_check
CHECK (
  alert_type IN (
    'esp32_offline',
    'esp32_online',

    'leak_detected',
    'leak_cleared',

    'dry_tank',
    'dry_tank_cleared',

    'low_tank',
    'tank_level_normal',

    'schedule_started',
    'schedule_completed',
    'schedule_failed',

    'valve_opened',
    'valve_closed',
    'valve_failed',

    'light_on',
    'light_off',
    'light_auto',
    'light_failed',

    'tank_refilled',

    'system_info'
  )
);


SELECT pg_get_constraintdef(oid)
FROM pg_constraint
WHERE conname = 'alerts_severity_check';


ALTER TABLE alerts
DROP CONSTRAINT IF EXISTS alerts_severity_check;

ALTER TABLE alerts
ADD CONSTRAINT alerts_severity_check
CHECK (
  severity IN (
    'critical',
    'warning',
    'info'
  )
);


SELECT
  id,
  alert_type,
  severity,
  message,
  is_resolved,
  created_at
FROM alerts
ORDER BY created_at DESC;


CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGSERIAL PRIMARY KEY,
  device_id BIGINT NULL,
  user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  actor_name VARCHAR(150),
  actor_role VARCHAR(30),
  action_type VARCHAR(100) NOT NULL,
  category VARCHAR(40) NOT NULL DEFAULT 'system',
  description TEXT NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'info',
  result VARCHAR(20) NOT NULL DEFAULT 'success',
  target_type VARCHAR(60),
  target_id VARCHAR(100),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_address VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT activity_logs_category_check
    CHECK (
      category IN (
        'authentication',
        'water',
        'lighting',
        'schedule',
        'user',
        'device',
        'report',
        'system'
      )
    ),

  CONSTRAINT activity_logs_severity_check
    CHECK (
      severity IN (
        'info',
        'success',
        'warning',
        'critical'
      )
    ),

  CONSTRAINT activity_logs_result_check
    CHECK (
      result IN (
        'success',
        'failed'
      )
    )
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at
  ON activity_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id
  ON activity_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_activity_logs_category
  ON activity_logs(category);

CREATE INDEX IF NOT EXISTS idx_activity_logs_severity
  ON activity_logs(severity);


SELECT
    table_name,
    ordinal_position,
    column_name,
    data_type,
    character_maximum_length,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY table_name, ordinal_position;


CREATE TABLE IF NOT EXISTS device_commands (
    id BIGSERIAL PRIMARY KEY,

    device_id INTEGER NOT NULL DEFAULT 1,

    command_type VARCHAR(30) NOT NULL,

    ward_number INTEGER,

    command_value VARCHAR(30),

    status VARCHAR(20) NOT NULL DEFAULT 'pending',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    picked_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    result TEXT
);

CREATE INDEX IF NOT EXISTS idx_device_commands_pending
ON device_commands(device_id, status, created_at);